version: '3.8'

services:
  cyberdome-sentinel:
    build: .
    container_name: cyberdome-sentinel
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=false
      - DATABASE_PATH=/app/data/filescanner.db
      - UPLOAD_FOLDER=/app/uploads
      - YARA_FOLDER=/app/yara-rules
      - MAX_CONTENT_LENGTH=104857600
      - MIN_COMMON_RULES=2
      - PAGINATION_OPTIONS=25,50,100,200
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./yara-rules:/app/yara-rules
      - ./static:/app/static
    networks:
      - cyberdome-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - cyberdome-redis

  cyberdome-redis:
    image: redis:7-alpine
    container_name: cyberdome-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cyberdome-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  cyberdome-nginx:
    image: nginx:alpine
    container_name: cyberdome-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./static:/var/www/static:ro
    networks:
      - cyberdome-network
    depends_on:
      - cyberdome-sentinel
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  cyberdome-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
